"""Add cascade delete for votes

Revision ID: 14ee17f9a895
Revises: 4a2446c2c75a
Create Date: 2025-06-25 22:05:34.535110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ee17f9a895'
down_revision: Union[str, None] = '4a2446c2c75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_votes_answer_id_fkey', 'answer_votes', type_='foreignkey')
    op.create_foreign_key(None, 'answer_votes', 'answers', ['answer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_votes_question_id_fkey', 'question_votes', type_='foreignkey')
    op.create_foreign_key(None, 'question_votes', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_votes', type_='foreignkey')
    op.create_foreign_key('question_votes_question_id_fkey', 'question_votes', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'answer_votes', type_='foreignkey')
    op.create_foreign_key('answer_votes_answer_id_fkey', 'answer_votes', 'answers', ['answer_id'], ['id'])
    # ### end Alembic commands ###
