"""Add webinar tables

Revision ID: 4a2446c2c75a
Revises: a24ec3a1ff43
Create Date: 2025-06-22 08:52:30.203870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2446c2c75a'
down_revision: Union[str, None] = 'a24ec3a1ff43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinars',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'ENDED', 'CANCELLED', name='webinarstatus'), nullable=False),
    sa.Column('plant_topic_id', sa.Integer(), nullable=True),
    sa.Column('jitsi_room_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plant_topic_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webinars_id'), 'webinars', ['id'], unique=False)
    op.create_index(op.f('ix_webinars_room_name'), 'webinars', ['room_name'], unique=True)
    op.create_table('webinar_participants',
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('HOST', 'MODERATOR', 'PARTICIPANT', name='participantrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webinar_participants_id'), 'webinar_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webinar_participants_id'), table_name='webinar_participants')
    op.drop_table('webinar_participants')
    op.drop_index(op.f('ix_webinars_room_name'), table_name='webinars')
    op.drop_index(op.f('ix_webinars_id'), table_name='webinars')
    op.drop_table('webinars')
    # ### end Alembic commands ###
