"""initial bd

Revision ID: a24ec3a1ff43
Revises: 
Create Date: 2025-05-19 10:08:59.839728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24ec3a1ff43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_zones',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_number', sa.Integer(), nullable=False),
    sa.Column('min_temperature', sa.Float(), nullable=True),
    sa.Column('max_temperature', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_zones_id'), 'climate_zones', ['id'], unique=False)
    op.create_index(op.f('ix_climate_zones_name'), 'climate_zones', ['name'], unique=True)
    op.create_index(op.f('ix_climate_zones_zone_number'), 'climate_zones', ['zone_number'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('plant_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['plant_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_categories_id'), 'plant_categories', ['id'], unique=False)
    op.create_index(op.f('ix_plant_categories_name'), 'plant_categories', ['name'], unique=True)
    op.create_table('plants',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latin_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('height_min', sa.Float(), nullable=True),
    sa.Column('height_max', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Enum('FAST', 'MODERATE', 'SLOW', name='growthrate'), nullable=True),
    sa.Column('plant_type', sa.Enum('TREE', 'SHRUB', 'FLOWER', 'VEGETABLE', 'FRUIT', 'HERB', 'SUCCULENT', 'VINE', 'AQUATIC', 'FERN', name='planttype'), nullable=True),
    sa.Column('life_cycle', sa.Enum('ANNUAL', 'BIENNIAL', 'PERENNIAL', name='lifecycle'), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=False),
    sa.Column('flowering_period', sa.String(length=100), nullable=True),
    sa.Column('bloom_color', sa.String(length=50), nullable=True),
    sa.Column('hardiness_zone_min', sa.Integer(), nullable=True),
    sa.Column('hardiness_zone_max', sa.Integer(), nullable=True),
    sa.Column('watering_frequency', sa.Enum('DAILY', 'TWICE_A_WEEK', 'WEEKLY', 'BI_WEEKLY', 'MONTHLY', 'RARELY', name='wateringfrequency'), nullable=True),
    sa.Column('light_level', sa.Enum('FULL_SUN', 'PARTIAL_SUN', 'SHADE', 'LOW_LIGHT', name='lightlevel'), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('humidity_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='humiditylevel'), nullable=True),
    sa.Column('care_difficulty', sa.Enum('VERY_EASY', 'EASY', 'MODERATE', 'DIFFICULT', 'EXPERT', name='caredifficulty'), nullable=True),
    sa.Column('fertilizing_frequency', sa.Enum('WEEKLY', 'BI_WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'NONE', name='fertilizingfrequency'), nullable=True),
    sa.Column('repotting_frequency', sa.Enum('ANNUALLY', 'BI_ANNUALLY', 'THREE_YEARS', 'RARELY', name='repottingfrequency'), nullable=True),
    sa.Column('is_toxic', sa.Boolean(), nullable=False),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('planting_instructions', sa.Text(), nullable=True),
    sa.Column('pruning_tips', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('care_tips', sa.Text(), nullable=True),
    sa.Column('common_problems', sa.Text(), nullable=True),
    sa.Column('propagation_methods', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plant_care_difficulty', 'plants', ['care_difficulty'], unique=False)
    op.create_index('idx_plant_type_popularity', 'plants', ['plant_type', 'popularity_score'], unique=False)
    op.create_index('idx_plant_watering_light', 'plants', ['watering_frequency', 'light_level'], unique=False)
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_index(op.f('ix_plants_name'), 'plants', ['name'], unique=False)
    op.create_index(op.f('ix_plants_plant_type'), 'plants', ['plant_type'], unique=False)
    op.create_index(op.f('ix_plants_popularity_score'), 'plants', ['popularity_score'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('privacy_level', sa.Enum('PUBLIC', 'LIMITED', 'PRIVATE', name='privacylevel'), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email_verification', 'users', ['email', 'is_verified'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_account')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_provider'), 'oauth_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_provider_user_id'), 'oauth_accounts', ['provider_user_id'], unique=False)
    op.create_index('ix_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'], unique=False)
    op.create_table('plant_category',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['plant_categories.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'category_id')
    )
    op.create_index('ix_plant_category_category', 'plant_category', ['category_id'], unique=False)
    op.create_index('ix_plant_category_plant', 'plant_category', ['plant_id'], unique=False)
    op.create_table('plant_climate_zone',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('climate_zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['climate_zone_id'], ['climate_zones.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'climate_zone_id')
    )
    op.create_index('ix_plant_climate_zone_climate', 'plant_climate_zone', ['climate_zone_id'], unique=False)
    op.create_index('ix_plant_climate_zone_plant', 'plant_climate_zone', ['plant_id'], unique=False)
    op.create_table('plant_images',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_images_id'), 'plant_images', ['id'], unique=False)
    op.create_table('plant_tag',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'tag_id')
    )
    op.create_index('ix_plant_tag_plant', 'plant_tag', ['plant_id'], unique=False)
    op.create_index('ix_plant_tag_tag', 'plant_tag', ['tag_id'], unique=False)
    op.create_table('questions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('votes_up', sa.Integer(), nullable=False),
    sa.Column('votes_down', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_title'), 'questions', ['title'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permission_permission', 'role_permission', ['permission_id'], unique=False)
    op.create_index('ix_role_permission_role', 'role_permission', ['role_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_role_role', 'user_role', ['role_id'], unique=False)
    op.create_index('ix_user_role_user', 'user_role', ['user_id'], unique=False)
    op.create_table('answers',
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('votes_up', sa.Integer(), nullable=False),
    sa.Column('votes_down', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('question_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_vote')
    )
    op.create_index(op.f('ix_question_votes_id'), 'question_votes', ['id'], unique=False)
    op.create_table('answer_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'answer_id', name='uq_user_answer_vote')
    )
    op.create_index(op.f('ix_answer_votes_id'), 'answer_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_votes_id'), table_name='answer_votes')
    op.drop_table('answer_votes')
    op.drop_index(op.f('ix_question_votes_id'), table_name='question_votes')
    op.drop_table('question_votes')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_user_role_user', table_name='user_role')
    op.drop_index('ix_user_role_role', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index('ix_role_permission_role', table_name='role_permission')
    op.drop_index('ix_role_permission_permission', table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_questions_title'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_plant_tag_tag', table_name='plant_tag')
    op.drop_index('ix_plant_tag_plant', table_name='plant_tag')
    op.drop_table('plant_tag')
    op.drop_index(op.f('ix_plant_images_id'), table_name='plant_images')
    op.drop_table('plant_images')
    op.drop_index('ix_plant_climate_zone_plant', table_name='plant_climate_zone')
    op.drop_index('ix_plant_climate_zone_climate', table_name='plant_climate_zone')
    op.drop_table('plant_climate_zone')
    op.drop_index('ix_plant_category_plant', table_name='plant_category')
    op.drop_index('ix_plant_category_category', table_name='plant_category')
    op.drop_table('plant_category')
    op.drop_index('ix_oauth_provider_user', table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_provider_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_provider'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_email_verification', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plants_popularity_score'), table_name='plants')
    op.drop_index(op.f('ix_plants_plant_type'), table_name='plants')
    op.drop_index(op.f('ix_plants_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_index('idx_plant_watering_light', table_name='plants')
    op.drop_index('idx_plant_type_popularity', table_name='plants')
    op.drop_index('idx_plant_care_difficulty', table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_plant_categories_name'), table_name='plant_categories')
    op.drop_index(op.f('ix_plant_categories_id'), table_name='plant_categories')
    op.drop_table('plant_categories')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_climate_zones_zone_number'), table_name='climate_zones')
    op.drop_index(op.f('ix_climate_zones_name'), table_name='climate_zones')
    op.drop_index(op.f('ix_climate_zones_id'), table_name='climate_zones')
    op.drop_table('climate_zones')
    # ### end Alembic commands ###
